version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:16.13.0
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
  test:
    docker:
      - image: circleci/node:16.13.0
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Lint test
          command: |
            npm run lint
            npm run test
  deploy:
    docker:
      - image: circleci/node:16.13.0
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Semantic Release
          command: npm run semantic-release
workflows:
  version: 2.1
  build-test-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          context: Environments
          requires:
            - test
          filters:
            branches:
              only:
                - master
                - beta
