name: '📚 Documentation Request'
description: Request a documentation update
title: '[Docs] '
labels: 'Type: Documentation'
assignees: skoropadas

body:
  - type: textarea
    id: description
    attributes:
      label: Description
      placeholder: |
        A clear and concise description of what the problem is. What kind of documentation update is needed or what is missing?
    validations:
      required: true
